namespace LEB_API.Models;

/// <summary>
/// Represents a note with its content, summary, and associated timestamps.
/// </summary>
public class Note
{
    /// <summary>
    /// Gets or sets the unique identifier of the note.
    /// </summary>
    public long Id { get; set; }

    /// <summary>
    /// Gets or sets the content of the note in HTML or plain text.
    /// </summary>
    public string Content { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the summary of the note, usually generated by an LLM.
    /// </summary>
    public string? Summary { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the date and time when the note was created.
    /// </summary>
    public DateTime? CreatedDate { get; set; } = default;

    /// <summary>
    /// Gets or sets the date and time when the note was last updated.
    /// </summary>
    public DateTime? UpdatedDate { get; set; } = default;

    /// <summary>
    /// Gets or sets the date and time when the note was last summarized.
    /// </summary>
    public DateTime? SummarizedDate { get; set; } = default;
}

